// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package databricks

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigHost      = "host"
	ConfigHttpPath  = "httpPath"
	ConfigPort      = "port"
	ConfigTableName = "tableName"
	ConfigToken     = "token"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigHost: {
			Default:     "",
			Description: "Databricks server hostname",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigHttpPath: {
			Default:     "",
			Description: "Databricks compute resources URL",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigPort: {
			Default:     "443",
			Description: "Databricks port",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{},
		},
		ConfigTableName: {
			Default:     "",
			Description: "Default table to which records will be written",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigToken: {
			Default:     "",
			Description: "Personal access token.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
